### ISSUE TITLE
Build failure during tests on Arch Linux

### ISSUE THREAD

**Issue by RGrun** [Malvineous/libgamemaps#2]
I get this when my package manager tries to install this library:

est-map2d.cpp(373): fatal error in "test_map2d::test_codelist[map_cosmo]": Map code 1 was not found in the list of permitted tiles for layer 2
test-map2d.cpp(373): fatal error in "test_map2d::test_codelist[map_jill]": Map code 1 was not found in the list of permitted tiles for layer 2
test-map2d.cpp(373): fatal error in "test_map2d::test_codelist[map_nukem2]": Map code 2 was not found in the list of permitted tiles for layer 3
test-map2d.cpp(373): fatal error in "test_map2d::test_codelist[map_xargon]": Map code 1 was not found in the list of permitted tiles for layer 2

**Comment by Malvineous** [comment]
This is a known issue.  The problem is not with your system, the problem is that those map formats haven't been fully implemented yet.  I left the errors in as a reminder to myself to finish them, however perhaps it is better to leave them out to avoid confusion.

**Comment by RGrun** [comment]
Thanks for the prompt reply.

I'd love it if you could. I'm trying to build Camoto Studio and this is the last dependency I need.

**Comment by Malvineous** [comment]
This will take a while as the library is currently being rewritten.  If you're on Arch Linux, you can pass the `--nocheck` option to `makepkg` or add `!check` to the `BUILDENV` option in `/etc/makepkg.conf` and it will skip these checks, which in this case is harmless.

**Comment by RGrun** [comment]
Thanks for the advice. I didn't know that.
